from typing import Any, Dict

from clusterinspector.profile.classify.externals import classify_externals
from clusterinspector.profile.output.yamlout import render_yaml


_HEADER = """\
# Auto-generated by clusterinspector — review before committing
# This is a starter for classes/<platform-class>/packages.yaml in the stack repo.
# Next steps:
#   1. Fill in any placeholder <module/VERSION> entries
#   2. Add Linux system library externals:
#      spack external find openssl curl zlib git cmake perl python m4 autoconf automake
#   3. For FIPS sites: ensure openssl is buildable: false with prefix: /usr
#
"""


def render_spack_packages(payload: Dict[str, Any]) -> str:
    """Render a Spack packages.yaml from a profile or multi-profile payload."""
    profiles = payload.get("profiles")
    if isinstance(profiles, list) and profiles:
        profile = profiles[0]
    else:
        profile = payload

    packages_dict = classify_externals(profile)
    return _HEADER + render_yaml(packages_dict)
