from typing import Any, Dict

from clusterinspector.profile.classify.externals import classify_externals
from clusterinspector.profile.output.yamlout import render_yaml


_HEADER_TEMPLATE = """\
# Auto-generated by clusterinspector — review before committing
# This is a starter for classes/<platform-class>/packages.yaml in the stack repo.
#
# GPU architecture for Kokkos/RAJA cmake flags: {gpu_arch_hint}
#
# Next steps:
#   1. Fill in any placeholder <module/VERSION> entries
#   2. Add minimum Linux system library externals (targeted list only):
#      spack external find openssl cmake m4 git perl pkgconf
#   3. For FIPS sites: ensure openssl is buildable: false with prefix: /usr
#   4. Do NOT run spack external find without arguments — it over-discovers on Cray
#
"""


def render_spack_packages(payload: Dict[str, Any]) -> str:
    """Render a Spack packages.yaml from a profile or multi-profile payload."""
    profiles = payload.get("profiles")
    if isinstance(profiles, list) and profiles:
        profile = profiles[0]
    else:
        profile = payload

    result = classify_externals(profile)
    gpu_arch_hint = result.get("gpu_arch_hint") or "(not detected — check hardware.gpus.compute_capability)"
    packages_dict = {"packages": result["packages"]}

    header = _HEADER_TEMPLATE.format(gpu_arch_hint=gpu_arch_hint)
    return header + render_yaml(packages_dict)
